# Generated by Django 3.2.6 on 2023-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zotitem',
            name='abstract_note',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'abstractNote' field.", null=True, verbose_name='abstract note'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='access_date',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'accessDate' field.", null=True, verbose_name='access date'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='archive',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'archive' field.", null=True, verbose_name='archive'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='archive_location',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'archiveLocation' field.", null=True, verbose_name='archive location'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='call_number',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'callNumber' field.", null=True, verbose_name='call number'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='citation',
            field=models.TextField(blank=True, help_text="Stores the item's citation representation. Pass ", verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='collections',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'collections' field.", null=True, verbose_name='collection'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='conference_name',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'conferenceName' field.", null=True, verbose_name='conference name'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='date_added',
            field=models.DateTimeField(blank=True, help_text="Stores all information from Zotero's 'dateAdded' field.", null=True, verbose_name='dateAdded'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='doi',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'DOI' field.", null=True, verbose_name='doi'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='edition',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'edition' field.", null=True, verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='extra',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'extra' field.", null=True, verbose_name='extra'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='isbn',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'ISBN' field.", null=True, verbose_name='isbn'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='issn',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'ISSN' field.", null=True, verbose_name='issn'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='issue',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'issue' field.", null=True, verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='journal_abbreviation',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'journalAbbreviation' field.", null=True, verbose_name='journal abbreviation'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='language',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'language' field.", null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='library_catalog',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'libraryCatalog' field.", null=True, verbose_name='library catalog'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='number_of_volumes',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'numberOfVolumes' field.", null=True, verbose_name='number of volumes'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='place',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'place' field.", null=True, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='proceedings_title',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'proceedingsTitle' field.", null=True, verbose_name='proceedings title'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='publisher',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'publisher' field.", null=True, verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='rights',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'rights' field.", null=True, verbose_name='rights'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='series',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'series' field.", null=True, verbose_name='series'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='series_number',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'seriesNumber' field.", null=True, verbose_name='series number'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='short_title',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'shortTitle' field.", null=True, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='tags',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'tags' field.", null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='url',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'url' field.", null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='zotitem',
            name='volume',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'volume' field.", null=True, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text="Stores all information from Zotero's 'dateModified' field.", null=True, verbose_name='dateModified'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_api_link',
            field=models.CharField(blank=True, help_text="Stores all information from Zotero's self api link field.", max_length=500, verbose_name='selflink api'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_creator',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'creators' field.", verbose_name='creators'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_date',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'date' field.", verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_html_link',
            field=models.CharField(blank=True, help_text="Stores all information from Zotero's 'selflink' field.", max_length=500, verbose_name='selflink html'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_item_type',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'itemType' field.", verbose_name='itemType'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_pages',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'numPages' field.", verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_title',
            field=models.TextField(blank=True, help_text="Stores all information from Zotero's 'title' field.", verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='zotitem',
            name='zot_version',
            field=models.IntegerField(blank=True, help_text="Stores all information from Zotero's 'version' field.", null=True, verbose_name='version'),
        ),
    ]